---
title: "Wildebeest"
output: html_document
---

```{r load packages, include=FALSE}
library(tidyverse)
library(lubridate)
library(amt)
library(rgdal)
library(here)
library(adehabitatLT)
library(wildlifeDI)
library(grid)
library(gridExtra)
library(ggplot2)
library(cowplot)
library(readxl)
library(adehabitatHR)
library(survival)
library(dynsurv)
library(splines)
library(dynamichazard)
library(lubridate)
library(segclust2d)
library(TTR)
library(zoo)
library(viridis)
library(ggnewscale)
library(colorspace)
source("./functions.R")
library(ggsn)
# library(CRS)
Sys.setlocale("LC_ALL", "English")

data_wildebeest = readRDS(file=here("./0_Ecology_submission/Data/wildebeest_dataset/data_wildebeest_1.rds"))
utm_string <- "+proj=utm +zone=36 +south +datum=WGS84 +ellps=WGS84 +units=m +no_defs"

n_control = 100
r_water_HiP = raster(here("./0_Ecology_submission/Data/wildebeest_dataset/dist_eau.tif"))
r_water_map = r_water_HiP
names(r_water_HiP) = "water"
g_water = ggplot(gplot_data(r_water_HiP))+
  geom_raster(aes(x,y, fill = value))+
    scale_fill_distiller(name="Water",
                         palette = "Blues",
                         na.value = NA)


r_vegetation_cover_HiP = raster(here("./0_Ecology_submission/Data/wildebeest_dataset/vegetation_cover.tif"))
r_open_vegetation_HiP = abs(1-r_vegetation_cover_HiP)
names(r_open_vegetation_HiP) = "open_vg"
g_vegetation = ggplot()+
    geom_raster(data = gplot_data(r_open_vegetation_HiP),
                aes(x, y, fill  = value), alpha = 1)+
    scale_fill_gradient2(low = "darkgreen", mid = "green4", high = "white",
                         name="Open habitat",limits=c(0,1), na.value = NA)

```


# Day-night period
migration ind = 12
```{r wildebeest day-night, echo = F, eval = T}


data_id = data_wildebeest %>% 
  mutate(x = x_, y=y_,
         date = format(t_,format='%Y-%m-%d')) %>% 
  filter((month(t_) == 8 & day(t_) > 17) | (month(t_) == 9 & day(t_) < 15))


xy = SpatialPointsDataFrame(coords = data_id[,c("x_","y_")],
                            data = data.frame("name" = data_id$animalID,
                                              "date" = as.POSIXct(data_id$date_time_utc)))
raster::crs(xy) = utm_string
df_F2 <- fortify(getverticeshr(kernelUD(xy[,1], h="href"), percent = 90, unout = "km2"))

gs = ggplot() +
  geom_raster(data = gplot_data(r_water_HiP) %>% 
                  mutate(prox_water = ifelse(value < 1, "<1km", ">1km"),
                         prox_water = ifelse(value < 0.1, "<100m", prox_water)),
                aes(x,y, fill = prox_water))+
  scale_fill_manual(values = c("#4575b4","#abd9e9", "#fdae61"))+
  geom_path(data = data_id, aes(x,y))+
  geom_point(data = data_id, aes(x,y, col = factor(Day_Night)))+
  scale_color_viridis_d(direction = -1)+
  xlim(min(data_id$x)-500, max(data_id$x)+500)+
  ylim(min(data_id$y)-500, max(data_id$y)+500)+
  theme_bw()+
  ggsn::scalebar( data = df_F2,
                  dist = 0.5, dist_unit = "km", transform = FALSE, st.size = 3, height = 0.01,box.fill=c("#000000"))+
  labs(fill = "Distance to river", colour = "Day-Night")+
      theme(strip.text = element_text(size=10, face="bold"),
            axis.title.y=element_text(size=10, face="bold", angle = 90),
          axis.title.x=element_text(size=10, face="bold"),
          axis.text=element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10, face="bold"))+
  xlab("Easting (UTM)")+
  ylab("Northing (UTM)")

png(here("./0_Ecology_submission/Figure/Supplemental_Application_diel.png"),
    height = 12, width = 18, units = "cm", res = 600)
gs
dev.off()


df_dd = Dynamic_RSF(data_id, BY = 1, application = "diel")

data_id <- data_id %>% 
  mutate(numeric_time = 1:nrow(data_id))
data <- left_join(df_dd, data_id, by = c("t" = "numeric_time"))


data_breaks_night <- data %>% 
  group_by(date) %>% 
  filter(row_number() == 1) %>%
  ungroup() %>%
  mutate(start = update(t_, hour = Sunset),
         end = update(lead(t_), hour = Sunrise),
         colors = "night") %>% 
  dplyr::select(start, end, colors)

data_breaks_day <- data %>% 
  group_by(date) %>% 
  filter(row_number() == 1) %>%
  ungroup() %>%
  mutate(start = update(t_, hour = Sunrise),
         end = update(t_, hour = Sunset),
         colors = "day") %>% 
  dplyr::select(start, end, colors)

data_breaks = rbind(data_breaks_night, data_breaks_day)
data_breaks <- data_breaks[order(data_breaks$start),]

df_data = rbind(
  data %>% 
    mutate(beta = open_vg , beta_lower = open_vg_lower95 , beta_upper = open_vg_upper95, type = "open") %>% 
    dplyr::select(beta,beta_lower,beta_upper, t_, type),
  data %>% 
    mutate(beta = water, beta_lower = water_lower95, beta_upper = water_upper95, type = "water") %>% 
    dplyr::select(beta,beta_lower,beta_upper, t_, type))
  
dose.labs <- c("Open habitat","Distance to water")
names(dose.labs) <- c("open","water")
g1_t_diel = ggplot(df_data %>% filter(type == "open"))+
    geom_rect(data = data_breaks_night,
              aes(xmin = start,
                  xmax = end,
                  ymin = -Inf,
                  ymax = Inf,
                  fill = colors),alpha = 0.3) +
    scale_fill_manual(values = "grey50")+
    new_scale_fill() +
    geom_ribbon(aes(x=t_, y=beta, ymin=beta_lower, ymax=beta_upper, fill = "Estimated"), alpha = 0.5)+
    geom_line(aes(x=t_, y=beta, col = "Estimated"), lwd = 1.1)+
    geom_hline(yintercept = 0, linetype = "dashed", lwd = 1)+
    theme_classic()+
    theme(strip.text = element_text(size=10, face="bold"),
          plot.title = element_blank(),
          axis.title=element_text(size=10, face="bold"),
          axis.text=element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10, face="bold"),
          legend.position = "none")+
    xlab("Time")+
    ylab("Coefficient \n (habitat openness)")+
    scale_color_viridis(discrete = T)+
    scale_fill_viridis(discrete = T)+
    scale_x_datetime(date_labels = "%d %b")

g2_t_diel = ggplot(df_data %>% filter(type == "water"))+
    geom_rect(data = data_breaks_night,
              aes(xmin = start,
                  xmax = end,
                  ymin = -Inf,
                  ymax = Inf,
                  fill = colors),alpha = 0.3) +
    scale_fill_manual(values = "grey50")+
    new_scale_fill() +
    geom_ribbon(aes(x=t_, y=beta, ymin=beta_lower, ymax=beta_upper, fill = "Estimated"), alpha = 0.5)+
    geom_line(aes(x=t_, y=beta, col = "Estimated"), lwd = 1.1)+
    geom_hline(yintercept = 0, linetype = "dashed", lwd = 1)+
    theme_classic()+
    theme(strip.text = element_text(size=10, face="bold"),
          plot.title = element_blank(),
          axis.title=element_text(size=10, face="bold"),
          axis.text=element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10, face="bold"),
          legend.position = "none")+
    xlab("Time")+
    ylab("Coefficient \n (distance to river)")+
    scale_color_viridis(discrete = T)+
    scale_fill_viridis(discrete = T)+
    scale_x_datetime(date_labels = "%d %b")


g0 = plot_grid(g1_t_diel, g2_t_diel, ncol = 1)
g0

png(here("./0_Ecology_submission/Figure/Application_diel.png"),
    height = 12, width = 18, units = "cm", res = 600)
g0
dev.off()


saveRDS(g1_t_diel, here("./0_Ecology_submission/Figure/g1_t_diel.rds"))
saveRDS(g2_t_diel, here("./0_Ecology_submission/Figure/g2_t_diel.rds"))


data_ts <- data %>% 
  mutate(round_date = lubridate::round_date(t_, "15 minutes") ) %>% 
  dplyr::select(round_date, open_vg) %>% 
  arrange(round_date) %>%
  filter(!duplicated(round_date) )

ts_beta1 <- zoo(data_ts$open_vg, order.by = data_ts$round_date) 


acf_beta1 = acf(ts_beta1, lag.max = 4*24*2, plot = F)

data_acf1 = data.frame(lag = acf_beta1$lag,
                      acf = acf_beta1$acf,
                      type = "open_vg")


g_acf = ggplot(data = data_acf1, aes(x = lag/4, y = acf)) +
       geom_hline(aes(yintercept = 0)) +
       geom_segment(mapping = aes(xend = lag/4, yend = 0))+
  theme_bw()+
  xlab("Time lag (hours)")+
  ylab("Autocorrelation \n (habitat openness)")+
  ylim(-1,1)+
  theme(strip.text = element_text(size=10, face="bold"),
        plot.title = element_blank(),
        axis.title=element_text(size=10, face="bold"),
        axis.text=element_text(size=10),
        legend.text = element_text(size=10),
        legend.title = element_text(size=10, face="bold"))


png(here("./0_Ecology_submission/Figure/Application_diel_Supplemental.png"),
    height = 7, width = 8.5, units = "cm", res = 300)
g_acf
dev.off()

```



```{r wildebeest season, echo = F, eval = T}

data_id = data_wildebeest %>% 
  mutate(date = format(t_,format='%Y-%m-%d')) %>% 
  group_by(date, hour(t_)) %>%
  filter(row_number() == 1) %>% 
  ungroup() %>%
  mutate(x = x_, y=y_)

gmvt = ggplot() + 
  geom_path(data = data_id, aes(x_,y_))+
  geom_point(data = data_id, aes(x_,y_, col = as.Date(t_)))+
  scale_color_viridis( labels=as.Date)+
  xlim(min(data_id$x_, na.rm = T)-1000, max(data_id$x_, na.rm = T)+1000)+
  ylim(min(data_id$y_, na.rm = T)-1000, max(data_id$y_, na.rm = T)+1000)
print(gmvt)

xy = SpatialPointsDataFrame(coords = data_id[,c("x_","y_")],
                            data = data.frame("name" = data_id$animalID,
                                              "date" = as.POSIXct(data_id$date_time_utc)))
raster::crs(xy) = utm_string
df_F2 <- fortify(getverticeshr(kernelUD(xy[,1], h="href"), percent = 95, unout = "km2"))

gs2 = ggplot() +
  geom_path(data = data_id, aes(x_,y_))+
  geom_point(data = data_id, aes(x_,y_, col = as.Date(t_)))+
  scale_color_viridis( labels=as.Date)+
  theme_bw()+
  ggsn::scalebar( data = df_F2,
                  dist = 5, dist_unit = "km", transform = FALSE, st.size = 3, height = 0.01,box.fill=c("#000000"))+
  labs(colour = "Time")+
      theme(strip.text = element_text(size=10, face="bold"),
            axis.title.y=element_text(size=10, face="bold", angle = 90),
          axis.title.x=element_text(size=10, face="bold"),
          axis.text=element_text(size=10),
          legend.text = element_text(size=10),
          legend.title = element_text(size=10, face="bold"))+
  xlab("Easting (UTM)")+
  ylab("Northing (UTM)")

png(here("./0_Ecology_submission/Figure/Supplemental_Application_seasonal.png"),
    height = 12, width = 18, units = "cm", res = 600)
gs2
dev.off()

data_output_HR = Shift_segment(data_id)
# data_phase = RSF_cst_phasis(data_output_HR)
data_phase = data_output_HR
# df_dd = Dynamic_RSF_xy(data_phase, BY = 1)
df_dd = Dynamic_RSF(data_phase, BY = 1, application = "season", n_control = 10)

data_phase <- data_phase %>% 
  mutate(numeric_time = 1:nrow(data_phase))
data <- left_join(df_dd, data_phase, by = c("t" = "numeric_time"))


data_breaks = data.frame(start = 
  c(as.POSIXct(data$t_[1]),as.POSIXct("2019-10-01"),as.POSIXct("2020-04-01")),
                         end = 
  c(as.POSIXct("2019-10-01"),as.POSIXct("2020-04-01"),as.POSIXct(data$t_[nrow(data)-1])),
  colors = c("Dry", "Wet", "Dry"))

data_breaks = data.frame(start = 
  c(as.POSIXct(-Inf),as.POSIXct("2019-10-01"),as.POSIXct("2020-04-01")),
                         end = 
  c(as.POSIXct("2019-10-01"),as.POSIXct("2020-04-01"),as.POSIXct(Inf)),
  colors = c("Dry", "Wet", "Dry"))

shift_beta1 <- segmentation(data.frame(data %>% dplyr::select(open_vg)),
                         seg.var = c("open_vg"),
                         lmin = 10, Kmax = 50,
                         subsample_by = 10)
shift_beta2 <- segmentation(data.frame(data %>% dplyr::select(water)),
                         seg.var = c("water"),
                         lmin = 10, Kmax = 50,
                         subsample_by = 10)
shift_beta3 <- segmentation(data.frame(data %>% dplyr::select(x_scale)),
                         seg.var = c("x_scale"),
                         lmin = 10, Kmax = 50,
                         subsample_by = 10)

data_output_HR = augment(shift_beta1)
  
data <- data %>% 
  mutate(beta_1_seg = augment(shift_beta1)$state,
         beta_2_seg = augment(shift_beta2)$state,
         beta_3_seg = augment(shift_beta3)$state)



data_segment = cbind(
  data %>% 
  group_by(beta_1_seg) %>% 
  filter(t_ == min(t_, na.rm = T)) %>% 
  dplyr::select(beta_1_seg, start=t_),
  data %>% 
  group_by(beta_1_seg) %>% 
  filter(t_ == max(t_, na.rm = T)) %>%
  ungroup() %>% 
  dplyr::select(end=t_))

g1_t_season = ggplot(data)+
  geom_rect(data = data_breaks,
            aes(xmin = (start),
                xmax = (end),
                ymin = -Inf,
                ymax = Inf,
                fill = colors),
            alpha = 0.2) +
    scale_fill_manual(values = c("#d73027", "#4575b4"))+
    new_scale_fill() +
    geom_rect(data = data_segment,
            aes(xmin = (start),
                xmax = (end),
                ymin = -Inf,
                ymax = -3.5,
                fill = factor(beta_1_seg)),
            alpha = 1) +
    geom_ribbon(aes(x=(t_), y=open_vg, ymin=open_vg_lower95, ymax=open_vg_upper95,
                    fill = factor(beta_1_seg)), alpha = 0.5)+
    geom_line(aes(x=(t_), y=open_vg, col = factor(beta_1_seg)), lwd = 1.1)+
    theme_classic()+
    theme(legend.position = "none",
        plot.title = element_blank(),
        axis.title=element_text(size=10, face="bold"),
        axis.text=element_text(size=10),
        legend.text = element_text(size=10),
        legend.title = element_text(size=10, face="bold"))+
    xlab("Time")+
    ylab("Coefficient \n (habitat openness)")+
    scale_color_viridis_d()+
    scale_fill_viridis_d()+
    geom_hline(yintercept = 0, linetype = "dashed", lwd = 1)


data_segment = cbind(
  data %>% 
  group_by(beta_2_seg) %>% 
  filter(t_ == min(t_, na.rm = T)) %>% 
  dplyr::select(beta_2_seg, start=t_),
  data %>% 
  group_by(beta_2_seg) %>% 
  filter(t_ == max(t_, na.rm = T)) %>%
  ungroup() %>% 
  dplyr::select(end=t_))

 g2_t_season =  ggplot(data)+
  geom_rect(data = data_breaks,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = colors), 
            alpha = 0.2) +
    scale_fill_manual(values = c("#d73027", "#4575b4"))+
    new_scale_fill() +
       geom_rect(data = data_segment,
            aes(xmin = (start),
                xmax = (end),
                ymin = -Inf,
                ymax = -6,
                fill = factor(beta_2_seg)),
            alpha = 1) +
    geom_ribbon(aes(x=(t_), y=water, ymin=water_lower95, ymax=water_upper95,
                    fill = factor(beta_2_seg)), alpha = 0.5)+
    geom_line(aes(x=(t_), y=water, col = factor(beta_2_seg)), lwd = 1.1)+
    theme_classic()+
    theme(legend.position = "none",
        plot.title = element_blank(),
        axis.title=element_text(size=10, face="bold"),
        axis.text=element_text(size=10),
        legend.text = element_text(size=10),
        legend.title = element_text(size=10, face="bold"))+
    xlab("Time")+
    ylab("Coefficient \n (distance to river)")+
    scale_color_viridis_d()+
    scale_fill_viridis_d()+
    geom_hline(yintercept = 0, linetype = "dashed", lwd = 1)

  data_segment = cbind(
  data %>% 
  group_by(beta_3_seg) %>% 
  filter(t_ == min(t_, na.rm = T)) %>% 
  dplyr::select(beta_3_seg, start=t_),
  data %>% 
  group_by(beta_3_seg) %>% 
  filter(t_ == max(t_, na.rm = T)) %>%
  ungroup() %>% 
  dplyr::select(end=t_))
 
  
 g3_t_season = ggplot(data)+
  geom_rect(data = data_breaks,
            aes(xmin = start,
                xmax = end,
                ymin = -Inf,
                ymax = Inf,
                fill = colors), 
            alpha = 0.2) +
    scale_fill_manual(values = c("#d73027", "#4575b4"))+
    new_scale_fill() +
          geom_rect(data = data_segment,
            aes(xmin = (start),
                xmax = (end),
                ymin = -Inf,
                ymax = -9.5,
                fill = factor(beta_3_seg)),
            alpha = 1) +
    geom_ribbon(aes(x=(t_), y=x_scale, ymin=x_scale_lower95, ymax=x_scale_upper95,
                    fill = factor(beta_3_seg)), alpha = 0.5)+
    geom_line(aes(x=(t_), y=x_scale, col = factor(beta_3_seg)), lwd = 1.1)+
    theme_classic()+
    theme(legend.position = "none",
        plot.title = element_blank(),
        axis.title=element_text(size=10, face="bold"),
        axis.text=element_text(size=10),
        legend.text = element_text(size=10),
        legend.title = element_text(size=10, face="bold"))+
    xlab("Time")+
    ylab("Coefficient \n (longitude)")+
    scale_color_viridis_d()+
    scale_fill_viridis_d()+
    geom_hline(yintercept = 0, linetype = "dashed", lwd = 1)

pg = plot_grid(g1_t_season, 
               g2_t_season,
               g3_t_season, ncol = 1)
pg

png(here("./0_Ecology_submission/Figure/seasonal_segmentation.png"), width = 18, height = 14, units = "cm", res = 600)
print(pg)
dev.off()


saveRDS(g1_t_season, here("./0_Ecology_submission/Figure/g1_t_season.rds"))
saveRDS(g2_t_season, here("./0_Ecology_submission/Figure/g2_t_season.rds"))
saveRDS(g3_t_season, here("./0_Ecology_submission/Figure/g3_t_season.rds"))


```



```{r wildebeest figure, echo = F, eval = T}

fig = plot_grid(g1_t_diel, g2_t_diel,
                g1_t_season,
                g2_t_season,
                ncol = 1,
                labels = c("(a)", "(b)", "(c)", "(d)"))


png(here("./0_Ecology_submission/Figure/Figure2.png"),
    width = 18, height = 24, units = "cm", res = 600)
print(fig)
dev.off()


```




